name: publish-style-spec

on:
  push:
    branches: [main]

jobs:
  build_publish:
    name: Build, publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2
        with:
          node-version: 14
          architecture: x64
          registry-url: 'https://registry.npmjs.org'

      - name: Install GL JS
        run: npm ci
      
      - name: Build GL JS
        run: |
          npm run build-prod-min
          npm run build-css
      
      - name: Build style spec
        run: |
          npm run build-style-spec
      
      - name: Deploy style spec
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/style-spec
          publish_branch: gh-pages-public
